### ISSUE TITLE
build failed after pod install

### ISSUE THREAD

**Issue by JQUERYLIN** [dsxNiubility/SXNews#30]
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JQUERYLIN** [comment]
我刚学OC开发1个月不到请赐教，环境：OS 10.11.5  XCODE 8.0 BETA，谢谢！

**Comment by dsxNiubility** [comment]
这个问题是有个.a文件link异常，把他删了就好了。 你再试试

**Comment by JQUERYLIN** [comment]
解决了，谢谢！
