### ISSUE TITLE
交流一下交互性能这块

### ISSUE THREAD

**Issue by BaiCan** [dsxNiubility/SXNews#37]
![image](https://cloud.githubusercontent.com/assets/8268339/18940055/0514bdaa-8638-11e6-8fdc-77f60256bc4c.png)

我比较好奇这一块的参数是怎么拼接的，因为我抓到的包，来查看如下图

![image](https://cloud.githubusercontent.com/assets/8268339/18940075/2373f2fc-8638-11e6-8cd7-9152100c9caa.png)

这个图这里的逻辑是对应上面的，你有这方面的研究吗，newrelic 和 OneAPM 的参数都是一样的

**Comment by dsxNiubility** [comment]
公司内部也有类似的库，就是监控那些指标，然后上传服务器，网页再做展示。

**Comment by BaiCanLin** [comment]
对的对的，就是这样的，你知道里面前面这些参数是根据什么逻辑配置的吗，我不清楚一些逻辑，清楚的话我就知道怎么实现了，求交流

**Comment by dsxNiubility** [comment]
你看下这篇博文 是你的问题么？ http://www.cnblogs.com/dsxniubility/p/5493117.html

**Comment by BaiCanLin** [comment]
不是的，这些我都做完了，我要做的是用户交互分析数据，慢交互那些，第一个：name = "Mobile/Activity/Name/" + "Display " + Activity类名  scope = null   							这里有出入 "scope": "Mobile/Activity/Name/Display LiveShowViewController"
第二个：name = "Mobile/Activity/Background/Name/" + "Display " + Activity类名  scope = null  包含这些等等的

**Comment by dsxNiubility** [comment]
你抓的这个是第三方性能平台的，猜测他们 name用来区分具体的监控项，比如某个方法。 scope用来记录一些环境参数和栈顶控制器，也就是将要展示到网页上的子菜单一层层点进去的path。 你这个“数据错位”的情况具体要他们逻辑怎么设定了
